<?php
/**
 * Handles the AJAX requests for the plugin.
 *
 * WordPress requires the methods to be static to be used as AJAX handlers.
 *
 * @class   Ajax_Handler
 * @package WC_Bsale
 */

namespace WC_Bsale;

defined( 'ABSPATH' ) || exit;

/**
 * Ajax_Handler class
 */
class Ajax_Handler {
	public function __construct() {
		add_action( 'wp_ajax_search_bsale_offices', array( $this, 'search_bsale_offices' ) );
		add_action( 'wp_ajax_search_bsale_document_types', array( $this, 'search_bsale_document_types' ) );
		add_action( 'wp_ajax_search_bsale_price_lists', array( $this, 'search_bsale_price_lists' ) );
		add_action( 'wp_ajax_search_bsale_taxes', array( $this, 'search_bsale_taxes' ) );
	}

	/**
	 * Search active Bsale offices by name and outputs the results as JSON in a format that can be used by the Select2 plugin.
	 *
	 * @return void
	 *
	 * @see search_bsale_data()
	 */
	public static function search_bsale_offices(): void {
		search_bsale_data( 'search_offices_by_name', __( 'There was an error getting the offices from Bsale', 'wc-bsale' ) );
	}

	/**
	 * Search active Bsale document types by name and outputs the results as JSON in a format that can be used by the Select2 plugin.
	 *
	 * @return void
	 *
	 * @see search_bsale_data()
	 */
	public static function search_bsale_document_types(): void {
		search_bsale_data( 'search_document_types_by_name', __( 'There was an error getting the document types from Bsale', 'wc-bsale' ) );
	}

	/**
	 * Search active Bsale price lists by name and outputs the results as JSON in a format that can be used by the Select2 plugin.
	 *
	 * @return void
	 *
	 * @see search_bsale_data()
	 */
	public static function search_bsale_price_lists(): void {
		search_bsale_data( 'search_price_lists_by_name', __( 'There was an error getting the price lists from Bsale', 'wc-bsale' ) );
	}

	/**
	 * Search active Bsale taxes by name and outputs the results as JSON in a format that can be used by the Select2 plugin.
	 *
	 * @return void
	 */
	public static function search_bsale_taxes(): void {
		search_bsale_data( 'search_taxes_by_name', __( 'There was an error getting the taxes from Bsale', 'wc-bsale' ) );
	}
}

/**
 * Search Bsale entities by name and outputs the results as JSON in a format that can be used by the Select2 plugin.
 *
 * This function is expected to be called by an AJAX handler, with the 'term' and 'security' parameters in the $_GET superglobal:
 * - The 'term' parameter is the search term that the user entered in the Select2 input.
 * - The 'security' parameter is the nonce that was generated by WordPress to verify the request.
 *
 * If there's an error getting the data from Bsale, the error message will be sent as a disabled option for the Select2 plugin with the $error_message as a prefix.
 *
 * @param string $search_method The method to call in the Bsale API client.
 * @param string $error_message The error message to display if there's an error.
 *
 * @return void
 */
function search_bsale_data( string $search_method, string $error_message ): void {
	if ( ! wp_verify_nonce( $_GET['security'], 'search_bsale_data' ) ) {
		wp_send_json( array(
			'results' => array(
				array(
					'id'       => '-1',
					'text'     => __( 'Invalid nonce', 'wc-bsale' ),
					'disabled' => true,
				),
			)
		) );

		wp_die();
	}

	$search_term = sanitize_text_field( $_GET['term'] );

	$b_sale_api_client = new Bsale\API_Client();

	if ( '' === $search_term ) {
		wp_send_json( array( 'results' => array() ) );

		wp_die();
	}

	try {
		$search_results = $b_sale_api_client->$search_method( $search_term );
	} catch ( \Exception $e ) {
		// Send an error message as a disabled option for the Select2 plugin
		wp_send_json( array(
			'results' => array(
				array(
					'id'       => '-1',
					'text'     => $error_message . ' : ' . $e->getMessage(),
					'disabled' => true,
				),
			),
		) );

		wp_die();
	}

	// Format the results in a way that can be used by the Select2 plugin
	$formatted_results = array_map( function ( $result ) {
		return array(
			'id'   => $result['id'],
			'text' => $result['name'],
		);
	}, $search_results );

	wp_send_json( array( 'results' => $formatted_results ) );

	wp_die();
}